---
title: "Regression Modeling" 
author: "Jonathan Salas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig_height: 6
    keep_md: true
---

```{r setup, include=FALSE}
library(knitr)
library(ggplot2)
library(emmeans)
library(medrc)
library(aomisc)
library(sfsmisc)
library(dplyr)
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = "~/R_Projects/Dose_Response")
```

# Start with a clean slate

```{r echo = F}
rm(list = ls(all.names = TRUE))
```

# Import the cleaned data - Point to the correct raw data directory

```{r echo = F}
working_dat_dir <-"data/processed/working_dr.RData"
```

## Import Subject Data
```{r echo = F}
load(working_dat_dir)
```

# Regression Fitting

## 15 kV Unipolar 20x5

### 2-Parameter Nonlinear Asymptotic Regression - NLS

#### Depth

```{r}
nls_depth_asymp_4 <- nls(
  depth ~ SSasympOrig(application_num, Asym, lrc),
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "20x5" &
              waveform == "unipolar")
)
```

```{r}
summary(nls_depth_asymp_4)
```

```{r}
temp <- working_dat |>
  filter(voltage == 15, pulse_seq == "20x5", waveform == "unipolar") 

ggplot(data = temp, aes(x = application_num, y = depth)) +
  geom_smooth(
    method = nls,
    se = F,
    data = temp,
    formula = depth ~ SSasympOrig(application_num, Asym, lrc),
  )
```

```{r}
troubleshooting_export <- temp |> dplyr::select(application_num, depth) |>
  filter(application_num < 7) |>
  rename(iv = application_num,
         dv = depth) 


```

# Reprex

```{r}
df <- structure(list(iv = c(1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 
2, 3, 4, 5, 6), dv = c(9.2, 8.5, 13.5, 15.8, 18.3, 17.7, 8.7, 
10.8, 14.3, 15, 18, 15.3, 8.7, 14.6, 14.8, 16.8, 15.8, 15.8)), row.names = c(NA, 
-18L), class = c("tbl_df", "tbl", "data.frame"))

drm_asymp <- drm(
  dv ~ iv,
  data = df,,
  fct = AR.2(names = c("Asym", "lrc"))
)

drm_asymp

ggplot(data = df, aes(x = iv, y = dv)) +
  geom_smooth(
    method = drm,
    se = F,
    data = df,
    method.args = list(fct = AR.2()),
  )

nls_asymp <- nls(
  dv ~ SSasympOrig(iv, Asym, lrc),
  data = df
)

nls_asymp

ggplot(data = df, aes(x = iv, y = dv)) +
  geom_smooth(
    method = nls,
    se = F,
    data = df
  )

ggplot(data = df, aes(x = iv, y = dv)) +
  geom_smooth(
    method = nls,
    se = F,
    data = df,
    method.args = list(formula = dv ~ SSasympOrig(iv, Asym, lrc)),
  )



```




# Version and Package Details

```{r echo=F}
paste(version$version.string, version$nickname)
paste0(
  "RStudio Version ",
  rstudioapi::versionInfo()$version,
  " ",
  rstudioapi::versionInfo()$release_name
) # RStudio Version
subset(data.frame(sessioninfo::package_info()),
       attached == TRUE,
       c(package, loadedversion)) # Loaded Packages
```

# When were these files last rewritten?

```{r}
date()
```