---
title: "Regression Modeling" 
author: "Jonathan Salas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    fig_height: 6
    keep_md: true
---

```{r setup, include=FALSE}
library(knitr)
library(sfsmisc)
library(emmeans)
library(aomisc)
library(ggplot2)
library(dplyr)
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = "~/R_Projects/Dose_Response")
```

# Start with a clean slate

```{r echo = F}
rm(list = ls(all.names = TRUE))
```

# Import the cleaned data - Point to the correct raw data directory

```{r echo = F}
working_dat_dir <-"data/processed/working_dr.RData"
```

# Aesthetics

```{r echo = F}
blank.plot <- theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), #this theme section generates a blank canvas
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.title = element_blank(),
        legend.justification="top")
```

## Import Subject Data
```{r echo = F}
load(working_dat_dir)
```

# Regression Fitting

## 15 kV Unipolar 3x12x3

### 2-Parameter Nonlinear Asymptotic Regression

#### Depth

```{r}
drm_depth_asymp_5 <- drm(
  depth ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"),
  fct = AR.2(names = c("Upper Limit", "Steepness"))
)
```

##### Model Selection 

```{r}
mselect(
  drm_depth_asymp_5,
  list(
    L.3(), #L.3 lower limit at dose 0 is fixed at 0
    LL.3(), #LL.3 lower limit at dose 0 is fixed at 0
    LL2.3(), #LL2.3 lower limit at dose 0 is fixed at 0
    AR.2(), #AR.2 lower limit at dose 0 is fixed at 0
    MM.2() #MM.2 lower limit at dose = 0 is fixed at 0
  ),
  linreg = TRUE
)
```

```{r}
drm_depth_ll_5 <- drm(
  depth ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"),
  fct = LL.3(names = c("b", "Upper Limit", "Inflection"))
)
```

```{r}
summary(drm_depth_asymp_5)
summary(drm_depth_ll_5)
```

```{r}
PR(drm_depth_asymp_5, c(seq_along(1:10)))
PR(drm_depth_ll_5, c(seq_along(1:10)))
```

```{r}
working_dat |>
  filter(voltage == 15, pulse_seq == "3x12x3", waveform == "unipolar") |>
  ggplot(data = _, aes(x = application_num, y = depth)) +
  geom_smooth(method = drm,
              method.args = list(fct = AR.2()),
              se = F) +
  geom_jitter(width = 0.2, size = 4, na.rm = T) + 
  scale_x_continuous(
    labels = unique(working_dat$application_num),
    breaks = unique(working_dat$application_num)
  ) +
  ggtitle("15kV 3x12x3 Unipolar") +
  xlab("Applications") +
  ylab("Depth (mm)") +
#  # labs(caption = "Caption") + 
  coord_cartesian(ylim=c(3, 18))+
  blank.plot 
#  theme(axis.text=element_text(size=40, face = "bold"),
#        axis.title=element_text(size=24,face="bold")) 

#ggsave("15kv3x12x3uni_depth.png",
#       path = "figures",
#       scale = 1,
#       width = 20,
#       height = 28,
#       units = "cm",
#       dpi = "retina",
#       limitsize = F)
```

### Full Depth Curve


```{r}
drm_full_depth_ll_5 <- drm(
  depth ~ pulses,
  data = full_curve_3x12x3,
  fct = LL2.4()
)
```

```{r}
mselect(
  drm_full_depth_ll_5,
  list(
    L.3(),
    L.4(),
    L.5(),
    LL.3(),
    LL2.3(),
    LL.4(),
    LL2.4(),
    LL.5(),
    LL2.5(),
    W1.4(),
    W2.4()
  ),
  linreg = T,
  icfct = BIC
)
```

```{r}
# https://www.r-bloggers.com/2019/11/five-parameters-logistic-regression/
drm_full_depth_5 <- drm(
  depth ~ pulses,
  data = full_curve_3x12x3,
#  fct = LL2.5(names = c("Slope", "Lower Limit", "Upper Limit", "C","Asymmetry"),
#              fixed = c(NA,NA,NA,NA,NA))
  fct = W1.4(names = c("b", "Lower Limit", "Upper Limit", "e")) 
)
```

```{r}
summary(drm_full_depth_5)
```


```{r}
depth_fitted <- as.data.frame(cbind(pulses = full_curve_3x12x3$pulses, predict(drm_full_depth_5, interval = "confidence", level = 0.95, vcov = sandwich))) |> unique()

ED50_pulses_pred <- as.data.frame(ED(drm_full_depth_5,50, interval = "delta", vcov = sandwich))

ED50_depth_pred <- as.data.frame(cbind("ED50_pulses" = ED50_pulses_pred$Estimate, (t(
  predict(
    #Predict depth as ED50 and return robust confidence intervals
    drm_full_depth_5,
    newdata = data.frame(pulses = ED50_pulses_pred$Estimate),
    interval = "confidence",
    vcov = sandwich
  )
)))) |> rename("ED50_depth"= Prediction)
```

```{r}
ggplot(data = NULL) +
  geom_smooth(
    data = full_curve_3x12x3,
    aes(x = pulses, y = depth),
    method = drm,
    method.args = list(fct = W1.4()),
    se = F,
    linetype = "dashed",
    color = "black"
  ) +
  geom_jitter(data = full_curve_3x12x3,
              aes(x = pulses, y = depth, color = pulses),
              size = 4) +
  scale_colour_distiller(palette = "Spectral", direction = 1) +
  geom_errorbar(
    data = depth_fitted,
    aes(
      x = pulses,
      y = Prediction,
      ymin = Lower,
      ymax = Upper
    ),
    width = .3
  ) +
  geom_point(
    data = ED50_depth_pred,
    aes(x = ED50_pulses, y = ED50_depth),
    size = 10,
    shape = 6,
    fill = "white",
    color = "black"
  ) +
  geom_point(data = ED50_depth_pred,
             aes(x = ED50_pulses, y = ED50_depth),
             size = 2) +
  geom_segment(data = ED50_pulses_pred,
               aes(
                 x = Lower,
                 y = 1,
                 xend = Upper,
                 yend = 1
               ),
               color = "blue") +
  scale_x_continuous(
    labels = c(
      unique(full_curve_3x12x3$pulse_seq),
      unique(full_curve_3x12x3$pulses[full_curve_3x12x3$pulses > 108])
    ),
    breaks = unique(full_curve_3x12x3$pulses),
    transform = "log2",
    guide = guide_axis(angle = -45)
  ) +
  labs(
    x = "log2(Pulses)",
    y = "Depth (mm)",
    title = "4-Parameter Weibull Type 1 - 3x12x3",
    caption = "Regression line with Robust 95% confidence Intervals and Observed Values"
  ) +
  blank.plot +
  theme(
    axis.text = element_text(size = 20, face = "bold"),
    axis.title = element_text(size = 24, face = "bold")
  ) 

ggsave("15kv3x12x3uni_full_depth.png",
       path = "figures",
       scale = 1,
       width = 28,
       height = 20,
       units = "cm",
       dpi = "retina",
       limitsize = F)
```


#### Diameter

```{r}
drm_diameter_asymp_5 <- drm(
  diameter ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"),
  fct = AR.2(names = c("Upper Limit", "Steepness"))
)
```

```{r}
rlm_diameter_asymp_5 <- rlm(
  diameter ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"),
)
```

```{r}
summary(drm_diameter_asymp_5)
summary(rlm_diameter_asymp_5)
```

```{r}
working_dat |>
  filter(voltage == 15, pulse_seq == "3x12x3", waveform == "unipolar") |>
  ggplot(data = _, aes(x = application_num, y = diameter)) +
  geom_smooth(method = drm,
              method.args = list(fct = AR.2()),
              se = F) +
#    geom_smooth(method = rlm,
#              se = F) +
  geom_jitter(width = 0.2, size = 4, na.rm = T) + 
  scale_x_continuous(
    labels = unique(working_dat$application_num),
    breaks = unique(working_dat$application_num)
  ) +
  ggtitle("15kV 3x12x3 Unipolar") +
  xlab("Applications") +
  ylab("Diameter (mm)") +
#  # labs(caption = "Caption") +
#  coord_cartesian(ylim=c(20,60)) +
  blank.plot 
#  theme(axis.text=element_text(size=40, face = "bold"),
#        axis.title=element_text(size=24,face="bold")) 

#ggsave("15kv20x5uni_diameter.png",
#       path = "figures",
#       scale = 1,
#       width = 20,
#       height = 28,
#       units = "cm",
#       dpi = "retina",
#       limitsize = F)
```

#### Depth/Diameter Ratio

```{r}
drm_depth_ratio_5 <- drm(
  diameter ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"),
  fct = AR.2(names = c("Upper Limit", "Steepness"))
)
```

```{r}
rlm_depth_ratio_5 <- rlm(
  depth_per_width ~ application_num,
  data = working_dat,
  subset = (voltage == 15 &
              pulse_seq == "3x12x3" & 
              waveform == "unipolar"))
```

```{r}
summary(drm_depth_ratio_5)
summary(rlm_depth_ratio_5)
f.robftest(rlm_depth_ratio_5,"application_num")
```

```{r}
working_dat |>
  filter(voltage == 15, pulse_seq == "3x12x3", waveform == "unipolar") |>
  ggplot(data = _, aes(x = application_num, y = depth_per_width)) +
  geom_jitter(width = 0.2, size = 4, na.rm = T) +
  geom_smooth(method = "rlm", se = T) +
  geom_smooth(method = drm,
              method.args = list(fct = AR.2()),
              se = F) +
  scale_x_continuous(
    labels = unique(working_dat$application_num),
    breaks = unique(working_dat$application_num)
  ) +
  ggtitle("15kV 3x12x3 Bipolar") +
  xlab("Applications") +
  ylab("Depth per Diameter") +
  #  # labs(caption = "Caption") +
  #  coord_cartesian(ylim=c(10,20)) +
  blank.plot 
```

# Version and Package Details

```{r echo=F}
paste(version$version.string, version$nickname)
paste0(
  "RStudio Version ",
  rstudioapi::versionInfo()$version,
  " ",
  rstudioapi::versionInfo()$release_name
) # RStudio Version
subset(data.frame(sessioninfo::package_info()),
       attached == TRUE,
       c(package, loadedversion)) # Loaded Packages
```

# When were these files last rewritten?

```{r}
date()
```